language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tomroyer/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tomroyer/docker-multi npm run test

after_success:
  - docker build -t tomroyer/multi-client ./client
  - docker build -t tomroyer/multi-server ./server
  - docker build -t tomroyer/multi-nginx ./nginx
  - docker build -t tomroyer/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tomroyer/multi-server
  - docker push tomroyer/multi-client
  - docker push tomroyer/multi-nginx
  - docker push tomroyer/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-588798687999"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY